### ISSUE TITLE
Feature Request - Label Rules Outcome (special characters)

### ISSUE THREAD

**Issue by orester** [Bastian-Kuhn/cmdb-syncer#13]
Due the fact that "omd create SITE" does not allow any hyphens in the site name, their should be an additional OUTCOME in label rules which allows to filter/replace that (replace hyphens with underscores) if the LABEL is used as a site name for example.

Example:

label: whatever
value: my-site-name -> my_site_name

Many THX & Regards,
Oliver

**Comment by Bastian-Kuhn** [comment]
Hello Oliver,

Thanks for the patch. I merged it to the 1.3.3 branch.

Best
Bastian
