### ISSUE TITLE
Bug - folder name capital letter

### ISSUE THREAD

**Issue by orester** [Bastian-Kuhn/cmdb-syncer#6]
Hi,

its not really a bug but  an minor cosmetic issue. The "export_to_cmk-v2" task creates folder names with capital letters ("Mysite" instead of "mysite") even if the site name  (folder name)  has been transformed to lower case using label rules.

![image](https://user-images.githubusercontent.com/22522988/176623006-c2cce9d7-ea97-4b11-9faa-c92af55aac5a.png)

![image](https://user-images.githubusercontent.com/22522988/176623377-3bce5061-78eb-45e2-8236-1e62924e8db5.png)

![image](https://user-images.githubusercontent.com/22522988/176623446-4c9a465f-5b7e-4784-9d6d-5457c1ae6ab0.png)

br
Oliver

**Comment by Bastian-Kuhn** [comment]
Hello Oliver,

in fact, that is not a nice behavior. The Folder Title should respect the label. So I changed that. 
The first letter of the Title is no longer capitalized.

Regards,
Bastian
